#!/usr/bin/env bash

function usage {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
}

if [ $# -lt 4 ]; then
  usage
fi

# Extract parameters
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

ssh -o StrictHostKeyChecking=no -i "$ssh_key" $username@$server_ip "mkdir -p ~/"

scp -i "$ssh_key" "$file_path" $username@$server_ip:~/

echo "File '$file_path' transferred successfully to user '$username' on server $server_ip"
